set sigs [list]
lappend sigs "tb_pcie_top.m_awvalid"
lappend sigs "tb_pcie_top.m_awaddr"
lappend sigs "tb_pcie_top.m_awid"
lappend sigs "tb_pcie_top.m_awlen"
lappend sigs "tb_pcie_top.m_awsize"
lappend sigs "tb_pcie_top.m_wvalid"
lappend sigs "tb_pcie_top.m_wdata"
lappend sigs "tb_pcie_top.m_wstrb"
lappend sigs "tb_pcie_top.m_wlast"
lappend sigs "tb_pcie_top.m_bready"
lappend sigs "tb_pcie_top.m_arvalid"
lappend sigs "tb_pcie_top.m_araddr"
lappend sigs "tb_pcie_top.m_arid"
lappend sigs "tb_pcie_top.m_arlen"
lappend sigs "tb_pcie_top.m_arsize"
lappend sigs "tb_pcie_top.m_rready"
lappend sigs "tb_pcie_top.s_awready"
lappend sigs "tb_pcie_top.s_wready"
lappend sigs "tb_pcie_top.s_bvalid"
lappend sigs "tb_pcie_top.s_bresp"
lappend sigs "tb_pcie_top.s_bid"
lappend sigs "tb_pcie_top.s_arready"
lappend sigs "tb_pcie_top.s_rvalid"
lappend sigs "tb_pcie_top.s_rdata"
lappend sigs "tb_pcie_top.s_rresp"
lappend sigs "tb_pcie_top.s_rlast"
lappend sigs "tb_pcie_top.s_rid"
lappend sigs "tb_pcie_top.pipe_tx_data"
lappend sigs "tb_pcie_top.pipe_tx_datak"
lappend sigs "tb_pcie_top.pipe_tx_rate"
lappend sigs "tb_pcie_top.pipe_tx_elecidle"
lappend sigs "tb_pcie_top.pipe_tx_compliance"
lappend sigs "tb_pcie_top.pipe_rx_polarity"
lappend sigs "tb_pcie_top.pipe_power_down"
gtkwave::addSignalsFromList $sigs
gtkwave::setZoomFactor -18
gtkwave::setWindowStartTime 0
