set sigs [list]
lappend sigs "tb_pcie_top.pcie_clk"
lappend sigs "tb_pcie_top.pcie_rst_n"
lappend sigs "tb_pcie_top.pipe_clk"
lappend sigs "tb_pcie_top.m_awready"
lappend sigs "tb_pcie_top.m_wready"
lappend sigs "tb_pcie_top.m_bvalid"
lappend sigs "tb_pcie_top.m_bresp"
lappend sigs "tb_pcie_top.m_bid"
lappend sigs "tb_pcie_top.m_arready"
lappend sigs "tb_pcie_top.m_rvalid"
lappend sigs "tb_pcie_top.m_rdata"
lappend sigs "tb_pcie_top.m_rresp"
lappend sigs "tb_pcie_top.m_rlast"
lappend sigs "tb_pcie_top.m_rid"
lappend sigs "tb_pcie_top.s_awvalid"
lappend sigs "tb_pcie_top.s_awaddr"
lappend sigs "tb_pcie_top.s_awid"
lappend sigs "tb_pcie_top.s_awlen"
lappend sigs "tb_pcie_top.s_awsize"
lappend sigs "tb_pcie_top.s_wvalid"
lappend sigs "tb_pcie_top.s_wdata"
lappend sigs "tb_pcie_top.s_wstrb"
lappend sigs "tb_pcie_top.s_wlast"
lappend sigs "tb_pcie_top.s_bready"
lappend sigs "tb_pcie_top.s_arvalid"
lappend sigs "tb_pcie_top.s_araddr"
lappend sigs "tb_pcie_top.s_arid"
lappend sigs "tb_pcie_top.s_arlen"
lappend sigs "tb_pcie_top.s_arsize"
lappend sigs "tb_pcie_top.s_rready"
lappend sigs "tb_pcie_top.pipe_rx_data"
lappend sigs "tb_pcie_top.pipe_rx_datak"
lappend sigs "tb_pcie_top.pipe_rx_valid"
lappend sigs "tb_pcie_top.pipe_rx_elecidle"
lappend sigs "tb_pcie_top.pipe_rx_status"
lappend sigs "tb_pcie_top.pipe_phy_status"
gtkwave::addSignalsFromList $sigs
gtkwave::/Time/Zoom/Zoom_Full
gtkwave::/Time/Zoom/Zoom_In
gtkwave::/Time/Zoom/Zoom_In
gtkwave::/Time/Zoom/Zoom_In
