set sigs [list]
lappend sigs "tb_l2_cache_ctrl.s_arready"
lappend sigs "tb_l2_cache_ctrl.s_rvalid"
lappend sigs "tb_l2_cache_ctrl.s_rdata"
lappend sigs "tb_l2_cache_ctrl.s_rresp"
lappend sigs "tb_l2_cache_ctrl.s_awready"
lappend sigs "tb_l2_cache_ctrl.s_wready"
lappend sigs "tb_l2_cache_ctrl.s_bvalid"
lappend sigs "tb_l2_cache_ctrl.s_bresp"
lappend sigs "tb_l2_cache_ctrl.m_arvalid"
lappend sigs "tb_l2_cache_ctrl.m_araddr"
lappend sigs "tb_l2_cache_ctrl.m_rready"
lappend sigs "tb_l2_cache_ctrl.m_awvalid"
lappend sigs "tb_l2_cache_ctrl.m_awaddr"
lappend sigs "tb_l2_cache_ctrl.m_wvalid"
lappend sigs "tb_l2_cache_ctrl.m_wdata"
lappend sigs "tb_l2_cache_ctrl.m_wstrb"
lappend sigs "tb_l2_cache_ctrl.m_bready"
lappend sigs "tb_l2_cache_ctrl.tag_cs"
lappend sigs "tb_l2_cache_ctrl.tag_we"
lappend sigs "tb_l2_cache_ctrl.tag_index"
lappend sigs "tb_l2_cache_ctrl.tag_in"
lappend sigs "tb_l2_cache_ctrl.dat_cs"
lappend sigs "tb_l2_cache_ctrl.dat_we"
lappend sigs "tb_l2_cache_ctrl.dat_bank"
lappend sigs "tb_l2_cache_ctrl.dat_wmask"
lappend sigs "tb_l2_cache_ctrl.dat_addr"
lappend sigs "tb_l2_cache_ctrl.dat_din"
gtkwave::addSignalsFromList $sigs
gtkwave::setZoomFactor -18
gtkwave::setWindowStartTime 0
