set sigs [list]
lappend sigs "tb_gem_ethernet.m_awvalid"
lappend sigs "tb_gem_ethernet.m_awaddr"
lappend sigs "tb_gem_ethernet.m_awid"
lappend sigs "tb_gem_ethernet.m_awlen"
lappend sigs "tb_gem_ethernet.m_awsize"
lappend sigs "tb_gem_ethernet.m_wvalid"
lappend sigs "tb_gem_ethernet.m_wdata"
lappend sigs "tb_gem_ethernet.m_wstrb"
lappend sigs "tb_gem_ethernet.m_wlast"
lappend sigs "tb_gem_ethernet.m_bready"
lappend sigs "tb_gem_ethernet.m_arvalid"
lappend sigs "tb_gem_ethernet.m_araddr"
lappend sigs "tb_gem_ethernet.m_arid"
lappend sigs "tb_gem_ethernet.m_arlen"
lappend sigs "tb_gem_ethernet.m_arsize"
lappend sigs "tb_gem_ethernet.m_rready"
lappend sigs "tb_gem_ethernet.prdata"
lappend sigs "tb_gem_ethernet.pready"
lappend sigs "tb_gem_ethernet.pslverr"
lappend sigs "tb_gem_ethernet.mac_irq"
lappend sigs "tb_gem_ethernet.gmii_txd"
lappend sigs "tb_gem_ethernet.gmii_tx_en"
lappend sigs "tb_gem_ethernet.gmii_tx_er"
lappend sigs "tb_gem_ethernet.clk"
lappend sigs "tb_gem_ethernet.tx_clk"
lappend sigs "tb_gem_ethernet.rx_clk"
lappend sigs "tb_gem_ethernet.rst_n"
lappend sigs "tb_gem_ethernet.m_awready"
lappend sigs "tb_gem_ethernet.m_wready"
lappend sigs "tb_gem_ethernet.m_bvalid"
lappend sigs "tb_gem_ethernet.m_bresp"
lappend sigs "tb_gem_ethernet.m_bid"
lappend sigs "tb_gem_ethernet.m_arready"
lappend sigs "tb_gem_ethernet.m_rvalid"
lappend sigs "tb_gem_ethernet.m_rdata"
lappend sigs "tb_gem_ethernet.m_rresp"
lappend sigs "tb_gem_ethernet.m_rlast"
lappend sigs "tb_gem_ethernet.m_rid"
lappend sigs "tb_gem_ethernet.paddr"
lappend sigs "tb_gem_ethernet.psel"
lappend sigs "tb_gem_ethernet.penable"
lappend sigs "tb_gem_ethernet.pwrite"
lappend sigs "tb_gem_ethernet.pwdata"
lappend sigs "tb_gem_ethernet.gmii_rxd"
lappend sigs "tb_gem_ethernet.gmii_rx_dv"
lappend sigs "tb_gem_ethernet.gmii_rx_er"
lappend sigs "tb_gem_ethernet.gmii_crs"
lappend sigs "tb_gem_ethernet.gmii_col"
gtkwave::addSignalsFromList $sigs
gtkwave::/Time/Zoom/Zoom_Full
gtkwave::/Time/Zoom/Zoom_In
gtkwave::/Time/Zoom/Zoom_In
gtkwave::/Time/Zoom/Zoom_In
