set sigs [list]
lappend sigs "tb_gem_ethernet.clk"
lappend sigs "tb_gem_ethernet.rst_n"
lappend sigs "tb_gem_ethernet.m_awready"
lappend sigs "tb_gem_ethernet.m_wready"
lappend sigs "tb_gem_ethernet.m_bvalid"
lappend sigs "tb_gem_ethernet.m_bresp"
lappend sigs "tb_gem_ethernet.m_bid"
lappend sigs "tb_gem_ethernet.m_arready"
lappend sigs "tb_gem_ethernet.m_rvalid"
lappend sigs "tb_gem_ethernet.m_rdata"
lappend sigs "tb_gem_ethernet.m_rresp"
lappend sigs "tb_gem_ethernet.m_rlast"
lappend sigs "tb_gem_ethernet.m_rid"
lappend sigs "tb_gem_ethernet.paddr"
lappend sigs "tb_gem_ethernet.psel"
lappend sigs "tb_gem_ethernet.penable"
lappend sigs "tb_gem_ethernet.pwrite"
lappend sigs "tb_gem_ethernet.pwdata"
lappend sigs "tb_gem_ethernet.tx_clk"
lappend sigs "tb_gem_ethernet.rx_clk"
lappend sigs "tb_gem_ethernet.gmii_rxd"
lappend sigs "tb_gem_ethernet.gmii_rx_dv"
lappend sigs "tb_gem_ethernet.gmii_rx_er"
lappend sigs "tb_gem_ethernet.gmii_crs"
lappend sigs "tb_gem_ethernet.gmii_col"
gtkwave::addSignalsFromList $sigs
gtkwave::setZoomFactor -18
gtkwave::setWindowStartTime 0
