set sigs [list]
lappend sigs "tb_rv_dcache.cpu_rdata"
lappend sigs "tb_rv_dcache.cpu_valid"
lappend sigs "tb_rv_dcache.cpu_stall"
lappend sigs "tb_rv_dcache.sc_success"
lappend sigs "tb_rv_dcache.m_arvalid"
lappend sigs "tb_rv_dcache.m_araddr"
lappend sigs "tb_rv_dcache.m_arlen"
lappend sigs "tb_rv_dcache.m_arsize"
lappend sigs "tb_rv_dcache.m_arburst"
lappend sigs "tb_rv_dcache.m_arlock"
lappend sigs "tb_rv_dcache.m_rready"
lappend sigs "tb_rv_dcache.m_awvalid"
lappend sigs "tb_rv_dcache.m_awaddr"
lappend sigs "tb_rv_dcache.m_awlen"
lappend sigs "tb_rv_dcache.m_awsize"
lappend sigs "tb_rv_dcache.m_awburst"
lappend sigs "tb_rv_dcache.m_wvalid"
lappend sigs "tb_rv_dcache.m_wdata"
lappend sigs "tb_rv_dcache.m_wstrb"
lappend sigs "tb_rv_dcache.m_wlast"
lappend sigs "tb_rv_dcache.m_bready"
lappend sigs "tb_rv_dcache.snoop_ack"
lappend sigs "tb_rv_dcache.snoop_data_valid"
lappend sigs "tb_rv_dcache.snoop_data"
lappend sigs "tb_rv_dcache.ecc_1bit"
lappend sigs "tb_rv_dcache.ecc_2bit"
gtkwave::addSignalsFromList $sigs
gtkwave::setZoomFactor -18
gtkwave::setWindowStartTime 0
