/home/anupam-sarashwat/rtl_verification_handoff/video/vdma/vdma.v
/home/anupam-sarashwat/rtl_verification_handoff/video/hdmi_ctrl/hdmi_ctrl.v
/home/anupam-sarashwat/rtl_verification_handoff/video/mipi_csi2_rx/mipi_csi2_rx.v
/home/anupam-sarashwat/rtl_verification_handoff/video/isp_pipeline/isp_pipeline.v
/home/anupam-sarashwat/rtl_verification_handoff/backend/rv_ptw/rv_ptw.v
/home/anupam-sarashwat/rtl_verification_handoff/backend/rv_pmp/rv_pmp.v
/home/anupam-sarashwat/rtl_verification_handoff/backend/plic/plic.v
/home/anupam-sarashwat/rtl_verification_handoff/backend/rv_execute/rv_execute.v
/home/anupam-sarashwat/rtl_verification_handoff/backend/rv_fpu/rv_fpu.v
/home/anupam-sarashwat/rtl_verification_handoff/backend/rv_core_top/rv_core_top.v
/home/anupam-sarashwat/rtl_verification_handoff/backend/rv_tlb/rv_tlb.v
/home/anupam-sarashwat/rtl_verification_handoff/backend/rv_dcache/rv_dcache.v
/home/anupam-sarashwat/rtl_verification_handoff/backend/clint/clint.v
/home/anupam-sarashwat/rtl_verification_handoff/backend/rv_writeback/rv_writeback.v
/home/anupam-sarashwat/rtl_verification_handoff/backend/rv_monitor_core/rv_monitor_core.v
/home/anupam-sarashwat/rtl_verification_handoff/backend/rv_mem/rv_mem.v
/home/anupam-sarashwat/rtl_verification_handoff/backend/rv_mmu/rv_mmu.v
/home/anupam-sarashwat/rtl_verification_handoff/backend/rv_debug/rv_debug.v
/home/anupam-sarashwat/rtl_verification_handoff/interconnect/axi4_crossbar/axi4_crossbar.v
/home/anupam-sarashwat/rtl_verification_handoff/interconnect/apb_bridge/apb_bridge.v
/home/anupam-sarashwat/rtl_verification_handoff/interconnect/axi4_to_ahb/axi4_to_ahb.v
/home/anupam-sarashwat/rtl_verification_handoff/interconnect/qos_controller/qos_controller.v
/home/anupam-sarashwat/rtl_verification_handoff/interconnect/ahb_to_apb/ahb_to_apb.v
/home/anupam-sarashwat/rtl_verification_handoff/interconnect/interconnect_mpu/mpu.v
/home/anupam-sarashwat/rtl_verification_handoff/interconnect/mmu_arbiter/mmu_arbiter.v
/home/anupam-sarashwat/rtl_verification_handoff/peripherals/pcie_top/pcie_top.v
/home/anupam-sarashwat/rtl_verification_handoff/peripherals/gpio_ctrl/gpio_ctrl.v
/home/anupam-sarashwat/rtl_verification_handoff/peripherals/i2c_master/i2c_master.v
/home/anupam-sarashwat/rtl_verification_handoff/peripherals/can_controller/can_controller.v
/home/anupam-sarashwat/rtl_verification_handoff/peripherals/gem_sgmii_pcs/gem_sgmii_pcs.v
/home/anupam-sarashwat/rtl_verification_handoff/peripherals/pcie_pipe_if/pcie_pipe_if.v
/home/anupam-sarashwat/rtl_verification_handoff/peripherals/gem_ethernet/gem_ethernet.v
/home/anupam-sarashwat/rtl_verification_handoff/peripherals/uart_16550/uart_16550.v
/home/anupam-sarashwat/rtl_verification_handoff/peripherals/trng/trng.v
/home/anupam-sarashwat/rtl_verification_handoff/peripherals/aes_engine/aes_engine.v
/home/anupam-sarashwat/rtl_verification_handoff/peripherals/watchdog_timer/watchdog_timer.v
/home/anupam-sarashwat/rtl_verification_handoff/peripherals/spi_master/spi_master.v
/home/anupam-sarashwat/rtl_verification_handoff/peripherals/sha256_engine/sha256_engine.v
/home/anupam-sarashwat/rtl_verification_handoff/peripherals/rtc/rtc.v
/home/anupam-sarashwat/rtl_verification_handoff/frontend/rv_decode/rv_decode.v
/home/anupam-sarashwat/rtl_verification_handoff/frontend/rv_icache/rv_icache.v
/home/anupam-sarashwat/rtl_verification_handoff/frontend/rv_bpu/rv_bpu.v
/home/anupam-sarashwat/rtl_verification_handoff/frontend/rv_fetch/rv_fetch.v
/home/anupam-sarashwat/rtl_verification_handoff/common/cdc_sync/cdc_sync.v
/home/anupam-sarashwat/rtl_verification_handoff/common/fifo_sync/fifo_sync.v
/home/anupam-sarashwat/rtl_verification_handoff/common/fifo_async/fifo_async.v
/home/anupam-sarashwat/rtl_verification_handoff/common/reset_sync/reset_sync.v
/home/anupam-sarashwat/rtl_verification_handoff/common/BUFX4/buf_macros.v
/home/anupam-sarashwat/rtl_verification_handoff/top/titan_x_top/titan_x_top.v
/home/anupam-sarashwat/rtl_verification_handoff/memory/l2_data_array/l2_data_array.v
/home/anupam-sarashwat/rtl_verification_handoff/memory/ddr_scheduler/ddr_scheduler.v
/home/anupam-sarashwat/rtl_verification_handoff/memory/l2_snoop_filter/l2_snoop_filter.v
/home/anupam-sarashwat/rtl_verification_handoff/memory/l2_cache_ctrl/l2_cache_ctrl.v
/home/anupam-sarashwat/rtl_verification_handoff/memory/ddr_ctrl_top/ddr_ctrl_top.v
/home/anupam-sarashwat/rtl_verification_handoff/memory/sram_512kx8_180nm/sram_512kx8_180nm.v
/home/anupam-sarashwat/rtl_verification_handoff/memory/sram_32x64_180nm/sram_32x64_180nm.v
/home/anupam-sarashwat/rtl_verification_handoff/memory/l2_cache_top/l2_cache_top.v
/home/anupam-sarashwat/rtl_verification_handoff/memory/l2_tag_array/l2_tag_array.v
/home/anupam-sarashwat/rtl_verification_handoff/memory/ddr_phy_if/ddr_phy_if.v
/home/anupam-sarashwat/rtl_verification_handoff/storage/usb_otg/usb_otg.v
/home/anupam-sarashwat/rtl_verification_handoff/storage/mmc_controller/mmc_controller.v
/home/anupam-sarashwat/rtl_verification_handoff/storage/qspi_controller/qspi_controller.v
/home/anupam-sarashwat/rtl_verification_handoff/security/envm_ctrl/envm_ctrl.v
/home/anupam-sarashwat/rtl_verification_handoff/security/drbg/drbg.v
/home/anupam-sarashwat/rtl_verification_handoff/security/ecdsa_engine/ecdsa_engine.v
/home/anupam-sarashwat/rtl_verification_handoff/security/secure_boot/secure_boot.v
