// SPDX-License-Identifier: Apache-2.0
// SMVDU-TITAN-X SoC — System-on-Chip Top-Level Integration
// Generated by Integration Script

`timescale 1ns/1ps

module titan_x_top (
    input  wire        clk,
    input  wire        rst_n,

    // DDR4 Interface
    output wire [15:0] ddr_addr,
    output wire [2:0]  ddr_ba,
    output wire [1:0]  ddr_bg,
    output wire        ddr_ck_p,
    output wire        ddr_ck_n,
    output wire        ddr_cke,
    output wire        ddr_cs_n,
    output wire        ddr_ras_n,
    output wire        ddr_cas_n,
    output wire        ddr_we_n,
    output wire        ddr_reset_n,
    output wire        ddr_odt,
    output wire        ddr_act_n,
    inout  wire [63:0] ddr_dq,
    inout  wire [7:0]  ddr_dqs_p,
    inout  wire [7:0]  ddr_dqs_n,

    // High-Speed Peripherals
    input  wire        pipe_clk,
    input  wire        eth_tx_clk,
    input  wire        eth_rx_clk,
    input  wire        ulpi_clk,

    // Video / Imaging
    input  wire        mipi_rxbyteclkhs,
    input  wire        hdmi_clk_pixel,
    input  wire        hdmi_clk_tmds,
    output wire        hdmi_tmds_clk_p,
    output wire        hdmi_tmds_clk_n,
    output wire [2:0]  hdmi_tmds_data_p,
    output wire [2:0]  hdmi_tmds_data_n,

    // Low-Speed Peripherals
    input  wire        rtc_clk,
    output wire [4:0]  uart_tx,
    input  wire [4:0]  uart_rx,
    output wire [1:0]  can_tx,
    input  wire [1:0]  can_rx
);

    // -------------------------------------------------------
    // Internal Signals & Routing
    // -------------------------------------------------------
    wire boot_pass, boot_fail;
    wire core_rst_n = rst_n & boot_pass;

    wire [31:0] plic_irq;
    wire [4:0]  timer_irq;
    wire [4:0]  sw_irq;
    
    // AXI Crossbar Definitions
    localparam NM = 15;
    localparam NS = 9;
    localparam AW = 40;
    localparam DW = 64;
    localparam IDW = 4;

    wire [NM-1:0]        axm_awvalid, axm_awready;
    wire [(NM*AW)-1:0]   axm_awaddr;
    wire [(NM*IDW)-1:0]  axm_awid;
    wire [NM-1:0]        axm_wvalid, axm_wready, axm_wlast;
    wire [(NM*DW)-1:0]   axm_wdata;
    wire [(NM*8)-1:0]    axm_wstrb;
    wire [NM-1:0]        axm_bvalid, axm_bready;
    wire [(NM*2)-1:0]    axm_bresp;
    wire [(NM*IDW)-1:0]  axm_bid;
    wire [NM-1:0]        axm_arvalid, axm_arready, axm_rlast;
    wire [(NM*AW)-1:0]   axm_araddr;
    wire [(NM*IDW)-1:0]  axm_arid;
    wire [NM-1:0]        axm_rvalid, axm_rready;
    wire [(NM*DW)-1:0]   axm_rdata;
    wire [(NM*2)-1:0]    axm_rresp;
    wire [(NM*IDW)-1:0]  axm_rid;

    wire [NS-1:0]        axs_awvalid, axs_awready;
    wire [(NS*AW)-1:0]   axs_awaddr;
    wire [(NS*IDW)-1:0]  axs_awid;
    wire [NS-1:0]        axs_wvalid, axs_wready, axs_wlast;
    wire [(NS*DW)-1:0]   axs_wdata;
    wire [(NS*8)-1:0]    axs_wstrb;
    wire [NS-1:0]        axs_bvalid, axs_bready;
    wire [(NS*2)-1:0]    axs_bresp;
    wire [(NS*IDW)-1:0]  axs_bid;
    wire [NS-1:0]        axs_arvalid, axs_arready, axs_rlast;
    wire [(NS*AW)-1:0]   axs_araddr;
    wire [(NS*IDW)-1:0]  axs_arid;
    wire [NS-1:0]        axs_rvalid, axs_rready;
    wire [(NS*DW)-1:0]   axs_rdata;
    wire [(NS*2)-1:0]    axs_rresp;
    wire [(NS*IDW)-1:0]  axs_rid;

    // Crossbar Instantiation
    axi4_crossbar #(
        .NM(NM), .NS(NS), .AW(AW), .DW(DW), .IDW(IDW)
    ) u_crossbar (
        .clk(clk), .rst_n(core_rst_n),
        .m_awvalid(axm_awvalid), .m_awready(axm_awready), .m_awaddr(axm_awaddr), .m_awid(axm_awid),
        .m_wvalid(axm_wvalid), .m_wready(axm_wready), .m_wdata(axm_wdata), .m_wstrb(axm_wstrb), .m_wlast(axm_wlast),
        .m_bvalid(axm_bvalid), .m_bready(axm_bready), .m_bresp(axm_bresp), .m_bid(axm_bid),
        .m_arvalid(axm_arvalid), .m_arready(axm_arready), .m_araddr(axm_araddr), .m_arid(axm_arid),
        .m_rvalid(axm_rvalid), .m_rready(axm_rready), .m_rdata(axm_rdata), .m_rresp(axm_rresp), .m_rlast(axm_rlast), .m_rid(axm_rid),
        .s_awvalid(axs_awvalid), .s_awready(axs_awready), .s_awaddr(axs_awaddr), .s_awid(axs_awid),
        .s_wvalid(axs_wvalid), .s_wready(axs_wready), .s_wdata(axs_wdata), .s_wstrb(axs_wstrb), .s_wlast(axs_wlast),
        .s_bvalid(axs_bvalid), .s_bready(axs_bready), .s_bresp(axs_bresp), .s_bid(axs_bid),
        .s_arvalid(axs_arvalid), .s_arready(axs_arready), .s_araddr(axs_araddr), .s_arid(axs_arid),
        .s_rvalid(axs_rvalid), .s_rready(axs_rready), .s_rdata(axs_rdata), .s_rresp(axs_rresp), .s_rlast(axs_rlast), .s_rid(axs_rid)
    );

    // Tie off unused masters
    genvar m;
    generate
        for (m = 13; m < 15; m = m + 1) begin : gen_unused_axim
            assign axm_awvalid[m] = 1'b0;
            assign axm_awaddr[m*40 +: 40] = 40'h0;
            assign axm_awid[m*4 +: 4] = 4'h0;
            assign axm_wvalid[m] = 1'b0;
            assign axm_wdata[m*64 +: 64] = 64'h0;
            assign axm_wstrb[m*8 +: 8] = 8'h0;
            assign axm_wlast[m] = 1'b0;
            assign axm_bready[m] = 1'b1;
            assign axm_arvalid[m] = 1'b0;
            assign axm_araddr[m*40 +: 40] = 40'h0;
            assign axm_arid[m*4 +: 4] = 4'h0;
            assign axm_rready[m] = 1'b1;
        end
    endgenerate

    // Tie off unused slaves
    genvar s;
    generate
        for (s = 3; s < 9; s = s + 1) begin : gen_unused_axis
            assign axs_awready[s] = 1'b1;
            assign axs_wready[s] = 1'b1;
            assign axs_bvalid[s] = 1'b0;
            assign axs_bresp[s*2 +: 2] = 2'b00;
            assign axs_bid[s*4 +: 4] = 4'h0;
            assign axs_arready[s] = 1'b1;
            assign axs_rvalid[s] = 1'b0;
            assign axs_rdata[s*64 +: 64] = 64'h0;
            assign axs_rresp[s*2 +: 2] = 2'b00;
            assign axs_rlast[s] = 1'b0;
            assign axs_rid[s*4 +: 4] = 4'h0;
        end
    endgenerate

    // Boot ROM on Slave 2
    axi_rom #(
        .HEX_FILE("/home/anupam-sarashwat/titan_x_firmware/firmware.hex")
    ) u_boot_rom (
        .clk(clk),
        .rst_n(rst_n),
        .s_arvalid(axs_arvalid[2]),
        .s_arready(axs_arready[2]),
        .s_araddr (axs_araddr[2*40 +: 40]),
        .s_arid   (axs_arid[2*4 +: 4]),
        .s_rvalid (axs_rvalid[2]),
        .s_rready (axs_rready[2]),
        .s_rdata  (axs_rdata[2*64 +: 64]),
        .s_rresp  (axs_rresp[2*2 +: 2]),
        .s_rlast  (axs_rlast[2]),
        .s_rid    (axs_rid[2*4 +: 4])
    );
    assign axs_awready[2] = 1'b1;
    assign axs_wready[2] = 1'b1;
    assign axs_bvalid[2] = 1'b0;
    assign axs_bresp[2*2 +: 2] = 2'b00;
    assign axs_bid[2*4 +: 4] = 4'h0;

    // -------------------------------------------------------
    // Cores 0-3 (RV64GC)
    // -------------------------------------------------------
    genvar c;
    generate
        for (c = 0; c < 4; c = c + 1) begin : gen_cores
            // imem (Masters 0..3) is read-only
            assign axm_awvalid[c] = 1'b0;
            assign axm_awaddr[c*40 +: 40] = 40'h0;
            assign axm_awid[c*4 +: 4] = 4'h0;
            assign axm_wvalid[c] = 1'b0;
            assign axm_wdata[c*64 +: 64] = 64'h0;
            assign axm_wstrb[c*8 +: 8] = 8'h0;
            assign axm_wlast[c] = 1'b0;
            assign axm_bready[c] = 1'b1;

            wire [7:0] imem_arlen;
            wire [2:0] imem_arsize;
            wire [1:0] imem_arburst;
            
            rv_core_top #(
                .HART_ID(c),
                .RESET_PC(64'h0000_0000_1000_0000)
            ) u_core (
                .clk(clk), .rst_n(core_rst_n),
                .irq_m_ext(plic_irq[c]), .irq_m_timer(timer_irq[c]), .irq_m_soft(sw_irq[c]),
                
                .imem_arvalid(axm_arvalid[c]), .imem_arready(axm_arready[c]), 
                .imem_araddr(axm_araddr[c*40 +: 40]), .imem_arlen(imem_arlen), 
                .imem_arsize(imem_arsize), .imem_arburst(imem_arburst),
                .imem_rvalid(axm_rvalid[c]), .imem_rready(axm_rready[c]), 
                .imem_rdata(axm_rdata[c*64 +: 64]), .imem_rresp(axm_rresp[c*2 +: 2]), .imem_rlast(axm_rlast[c]),

                .dmem_awvalid(axm_awvalid[c+4]), .dmem_awready(axm_awready[c+4]), .dmem_awaddr(axm_awaddr[(c+4)*40 +: 40]), 
                .dmem_awlen(), .dmem_awsize(), .dmem_awburst(),
                .dmem_wvalid(axm_wvalid[c+4]), .dmem_wready(axm_wready[c+4]), .dmem_wdata(axm_wdata[(c+4)*64 +: 64]), 
                .dmem_wstrb(axm_wstrb[(c+4)*8 +: 8]), .dmem_wlast(axm_wlast[c+4]),
                .dmem_bvalid(axm_bvalid[c+4]), .dmem_bready(axm_bready[c+4]), .dmem_bresp(axm_bresp[(c+4)*2 +: 2]),
                
                .dmem_arvalid(axm_arvalid[c+4]), .dmem_arready(axm_arready[c+4]), .dmem_araddr(axm_araddr[(c+4)*40 +: 40]), 
                .dmem_arlen(), .dmem_arsize(), .dmem_arburst(), .dmem_arlock(),
                .dmem_rvalid(axm_rvalid[c+4]), .dmem_rready(axm_rready[c+4]), .dmem_rdata(axm_rdata[(c+4)*64 +: 64]), 
                .dmem_rresp(axm_rresp[(c+4)*2 +: 2]), .dmem_rlast(axm_rlast[c+4])
            );
            assign axm_arid[c*4 +: 4] = c[3:0];
            assign axm_awid[(c+4)*4 +: 4] = c[3:0] + 4'd4;
            assign axm_arid[(c+4)*4 +: 4] = c[3:0] + 4'd4;
        end
    endgenerate

    // -------------------------------------------------------
    // Core 4 Monitor (RV64IMAC)
    // -------------------------------------------------------
    assign axm_awvalid[8] = 1'b0;
    assign axm_awaddr[8*40 +: 40] = 40'h0;
    assign axm_awid[8*4 +: 4] = 4'h8;
    assign axm_wvalid[8] = 1'b0;
    assign axm_wdata[8*64 +: 64] = 64'h0;
    assign axm_wstrb[8*8 +: 8] = 8'h0;
    assign axm_wlast[8] = 1'b0;
    assign axm_bready[8] = 1'b1;
    assign axm_arid[8*4 +: 4] = 4'h8;
    assign axm_awid[9*4 +: 4] = 4'h9;
    assign axm_arid[9*4 +: 4] = 4'h9;

    rv_monitor_core #(.HART_ID(4)) u_monitor (
        .clk(clk), .rst_n(core_rst_n),
        .irq_m_ext(plic_irq[4]), .irq_m_timer(timer_irq[4]), .irq_m_soft(sw_irq[4]),
        
        .imem_arvalid(axm_arvalid[8]), .imem_arready(axm_arready[8]), .imem_araddr(axm_araddr[8*40 +: 40]),
        .imem_rvalid(axm_rvalid[8]), .imem_rdata(axm_rdata[8*64 +: 64]), .imem_rresp(axm_rresp[8*2 +: 2]),
        
        .dmem_awvalid(axm_awvalid[9]), .dmem_awready(axm_awready[9]), .dmem_awaddr(axm_awaddr[9*40 +: 40]),
        .dmem_awlen(), .dmem_awsize(), .dmem_awburst(),
        .dmem_wvalid(axm_wvalid[9]), .dmem_wready(axm_wready[9]), .dmem_wdata(axm_wdata[9*64 +: 64]),
        .dmem_bvalid(axm_bvalid[9]), .dmem_bready(axm_bready[9]), .dmem_bresp(axm_bresp[9*2 +: 2])
    );
    assign axm_arvalid[9] = 1'b0;
    assign axm_araddr[9*40 +: 40] = 40'h0;

    // -------------------------------------------------------
    // Memory Subsystem (Slave 0)
    // -------------------------------------------------------
    wire [15:0] l2_dat_cs, l2_dat_we, l2_dat_bank, l2_dat_addr, l2_dat_din, l2_dat_dout;
    wire l2_dat_dout_valid;
    
    l2_cache_top u_l2_cache (
        .clk(clk), .rst_n(rst_n)
    );

    ddr_ctrl_top u_ddr_ctrl (
        .clk(clk), .rst_n(rst_n),
        .s_awvalid(axs_awvalid[0]), .s_awready(axs_awready[0]), .s_awaddr(axs_awaddr[0*40 +: 40]), 
        .s_awid(axs_awid[0*4 +: 4]), .s_awlen(8'h0), .s_awsize(3'h0),
        .s_wvalid(axs_wvalid[0]), .s_wready(axs_wready[0]), .s_wdata(axs_wdata[0*64 +: 64]), 
        .s_wstrb(axs_wstrb[0*8 +: 8]), .s_wlast(axs_wlast[0]),
        .s_bvalid(axs_bvalid[0]), .s_bready(axs_bready[0]), .s_bresp(axs_bresp[0*2 +: 2]), .s_bid(axs_bid[0*4 +: 4]),
        
        .s_arvalid(axs_arvalid[0]), .s_arready(axs_arready[0]), .s_araddr(axs_araddr[0*40 +: 40]), 
        .s_arid(axs_arid[0*4 +: 4]), .s_arlen(8'h0),
        .s_rvalid(axs_rvalid[0]), .s_rready(axs_rready[0]), .s_rdata(axs_rdata[0*64 +: 64]), 
        .s_rresp(axs_rresp[0*2 +: 2]), .s_rlast(axs_rlast[0]), .s_rid(axs_rid[0*4 +: 4]),
        
        .ddr_addr(ddr_addr), .ddr_ba(ddr_ba), .ddr_bg(ddr_bg),
        .ddr_ck_p(ddr_ck_p), .ddr_ck_n(ddr_ck_n), .ddr_cke(ddr_cke), .ddr_cs_n(ddr_cs_n),
        .ddr_ras_n(ddr_ras_n), .ddr_cas_n(ddr_cas_n), .ddr_we_n(ddr_we_n),
        .ddr_dq(ddr_dq), .ddr_dqs_p(ddr_dqs_p), .ddr_dqs_n(ddr_dqs_n)
    );

    // -------------------------------------------------------
    // AHB & APB Bridge (Slave 1)
    // -------------------------------------------------------
    wire [31:0] haddr, hwdata, hrdata;
    wire        hwrite, hready, hresp;
    wire [1:0]  htrans;
    wire [2:0]  hsize, hburst;

    axi4_to_ahb #(.AW(40), .DW(64), .IDW(4)) u_axi2ahb (
        .clk(clk), .rst_n(rst_n),
        .s_awvalid(axs_awvalid[1]), .s_awready(axs_awready[1]), .s_awaddr(axs_awaddr[1*40 +: 40]), .s_awid(axs_awid[1*4 +: 4]),
        .s_wvalid(axs_wvalid[1]),   .s_wready(axs_wready[1]),   .s_wdata(axs_wdata[1*64 +: 64]), .s_wstrb(axs_wstrb[1*8 +: 8]),
        .s_bvalid(axs_bvalid[1]),   .s_bready(axs_bready[1]),   .s_bresp(axs_bresp[1*2 +: 2]), .s_bid(axs_bid[1*4 +: 4]),
        .s_arvalid(axs_arvalid[1]), .s_arready(axs_arready[1]), .s_araddr(axs_araddr[1*40 +: 40]), .s_arid(axs_arid[1*4 +: 4]),
        .s_rvalid(axs_rvalid[1]),   .s_rready(axs_rready[1]),   .s_rdata(axs_rdata[1*64 +: 64]), .s_rresp(axs_rresp[1*2 +: 2]),
        .s_rlast(axs_rlast[1]),
        .haddr(haddr), .hwrite(hwrite), .htrans(htrans), .hsize(hsize), .hburst(hburst),
        .hwdata(hwdata), .hrdata({32'h0, hrdata}), .hready(hready), .hresp(hresp)
    );
    
    wire [31:0] paddr, pwdata;
    wire [63:0] prdata_mux;
    wire        psel, penable, pwrite;
    
    assign paddr = haddr;
    assign pwdata = hwdata[31:0];
    assign pwrite = hwrite;
    assign penable = htrans[1];
    assign psel = htrans[1];
    assign hrdata = prdata_mux[31:0];
    assign hready = 1'b1;
    assign hresp = 1'b0;

    // APB Address Decoder
    wire psel_uart0 = psel && (paddr[31:12] == 20'h10000);
    wire psel_uart1 = psel && (paddr[31:12] == 20'h10001);
    wire psel_uart2 = psel && (paddr[31:12] == 20'h10002);
    wire psel_uart3 = psel && (paddr[31:12] == 20'h10003);
    wire psel_uart4 = psel && (paddr[31:12] == 20'h10004);
    wire psel_rtc   = psel && (paddr[31:12] == 20'h10010);
    wire psel_gem   = psel && (paddr[31:12] == 20'h10020);
    wire psel_usb   = psel && (paddr[31:12] == 20'h10030);
    wire psel_mipi  = psel && (paddr[31:12] == 20'h10040);
    wire psel_isp   = psel && (paddr[31:12] == 20'h10050);
    wire psel_hdmi  = psel && (paddr[31:12] == 20'h10060);
    wire psel_drbg  = psel && (paddr[31:12] == 20'h20000);
    wire psel_aes   = psel && (paddr[31:12] == 20'h20010);
    wire psel_envm  = psel && (paddr[31:12] == 20'h20020);
    wire psel_boot  = psel && (paddr[31:12] == 20'h20030);
    wire psel_can0  = psel && (paddr[31:12] == 20'h30000);
    wire psel_can1  = psel && (paddr[31:12] == 20'h30001);

    wire [31:0] prdata_uart0, prdata_uart1, prdata_uart2, prdata_uart3, prdata_uart4;
    wire [31:0] prdata_rtc, prdata_gem, prdata_usb, prdata_mipi, prdata_isp, prdata_hdmi;
    wire [31:0] prdata_drbg, prdata_aes, prdata_envm, prdata_boot, prdata_can0, prdata_can1;

    assign prdata_mux = psel_uart0 ? {32'h0, prdata_uart0} :
                        psel_uart1 ? {32'h0, prdata_uart1} :
                        psel_uart2 ? {32'h0, prdata_uart2} :
                        psel_uart3 ? {32'h0, prdata_uart3} :
                        psel_uart4 ? {32'h0, prdata_uart4} :
                        psel_rtc   ? {32'h0, prdata_rtc} :
                        psel_gem   ? {32'h0, prdata_gem} :
                        psel_usb   ? {32'h0, prdata_usb} :
                        psel_mipi  ? {32'h0, prdata_mipi} :
                        psel_isp   ? {32'h0, prdata_isp} :
                        psel_hdmi  ? {32'h0, prdata_hdmi} :
                        psel_drbg  ? {32'h0, prdata_drbg} :
                        psel_aes   ? {32'h0, prdata_aes} :
                        psel_envm  ? {32'h0, prdata_envm} :
                        psel_boot  ? {32'h0, prdata_boot} :
                        psel_can0  ? {32'h0, prdata_can0} :
                        psel_can1  ? {32'h0, prdata_can1} : 64'h0;

    // -------------------------------------------------------
    // DMA Peripherals (Masters 10, 11, 12)
    // -------------------------------------------------------
    gem_ethernet u_gem (
        .clk(clk), .rst_n(rst_n), .tx_clk(eth_tx_clk), .rx_clk(eth_rx_clk),
        .m_awvalid(axm_awvalid[10]), .m_awready(axm_awready[10]), .m_awaddr(axm_awaddr[10*40 +: 40]), .m_awid(axm_awid[10*4 +: 4]),
        .m_wvalid(axm_wvalid[10]),   .m_wready(axm_wready[10]),   .m_wdata(axm_wdata[10*64 +: 64]),   .m_wstrb(axm_wstrb[10*8 +: 8]), .m_wlast(axm_wlast[10]),
        .m_bvalid(axm_bvalid[10]),   .m_bready(axm_bready[10]),   .m_bresp(axm_bresp[10*2 +: 2]),     .m_bid(axm_bid[10*4 +: 4]),
        .m_arvalid(axm_arvalid[10]), .m_arready(axm_arready[10]), .m_araddr(axm_araddr[10*40 +: 40]), .m_arid(axm_arid[10*4 +: 4]),
        .m_rvalid(axm_rvalid[10]),   .m_rready(axm_rready[10]),   .m_rdata(axm_rdata[10*64 +: 64]),   .m_rresp(axm_rresp[10*2 +: 2]), .m_rlast(axm_rlast[10]),
        .paddr(paddr), .psel(psel_gem), .penable(penable), .pwrite(pwrite), .pwdata(pwdata), .prdata(prdata_gem), .pready(), .pslverr(),
        .mac_irq(plic_irq[27]), .gmii_txd(), .gmii_tx_en(), .gmii_tx_er(), .gmii_rxd(8'h0), .gmii_rx_dv(1'b0), .gmii_rx_er(1'b0), .gmii_crs(1'b0), .gmii_col(1'b0)
    );

    pcie_top u_pcie (
        .pcie_clk(clk), .pcie_rst_n(rst_n), .pipe_clk(pipe_clk),
        .m_awvalid(axm_awvalid[11]), .m_awready(axm_awready[11]), .m_awaddr(axm_awaddr[11*40 +: 40]), .m_awid(axm_awid[11*4 +: 4]),
        .m_wvalid(axm_wvalid[11]),   .m_wready(axm_wready[11]),   .m_wdata(axm_wdata[11*64 +: 64]),   .m_wstrb(axm_wstrb[11*8 +: 8]), .m_wlast(axm_wlast[11]),
        .m_bvalid(axm_bvalid[11]),   .m_bready(axm_bready[11]),   .m_bresp(axm_bresp[11*2 +: 2]),     .m_bid(axm_bid[11*4 +: 4]),
        .m_arvalid(axm_arvalid[11]), .m_arready(axm_arready[11]), .m_araddr(axm_araddr[11*40 +: 40]), .m_arid(axm_arid[11*4 +: 4]),
        .m_rvalid(axm_rvalid[11]),   .m_rready(axm_rready[11]),   .m_rdata(axm_rdata[11*64 +: 64]),   .m_rresp(axm_rresp[11*2 +: 2]), .m_rlast(axm_rlast[11]), .m_rid(axm_rid[11*4 +: 4]),
        .pipe_tx_data(), .pipe_tx_datak(), .pipe_tx_rate(), .pipe_tx_elecidle(), .pipe_tx_compliance(),
        .pipe_rx_data(32'h0), .pipe_rx_datak(4'h0), .pipe_rx_polarity(), .pipe_power_down(), .pipe_rx_valid(1'b0), .pipe_rx_elecidle(1'b1), .pipe_rx_status(3'h0), .pipe_phy_status(1'b0)
    );
    assign axm_rid[10*4 +: 4] = 4'h0;

    usb_otg u_usb (
        .clk(clk), .rst_n(rst_n), .ulpi_clk(ulpi_clk),
        .m_awvalid(axm_awvalid[12]), .m_awready(axm_awready[12]), .m_awaddr(axm_awaddr[12*40 +: 40]), .m_awid(axm_awid[12*4 +: 4]), .m_awlen(), .m_awsize(),
        .m_wvalid(axm_wvalid[12]),   .m_wready(axm_wready[12]),   .m_wdata(axm_wdata[12*64 +: 64]),   .m_wstrb(axm_wstrb[12*8 +: 8]), .m_wlast(axm_wlast[12]),
        .m_bvalid(axm_bvalid[12]),   .m_bready(axm_bready[12]),   .m_bresp(axm_bresp[12*2 +: 2]),     .m_bid(axm_bid[12*4 +: 4]),
        .m_arvalid(axm_arvalid[12]), .m_arready(axm_arready[12]), .m_araddr(axm_araddr[12*40 +: 40]), .m_arid(axm_arid[12*4 +: 4]),
        .m_arlen(), .m_arsize(), .m_rvalid(axm_rvalid[12]), .m_rready(axm_rready[12]), .m_rdata(axm_rdata[12*64 +: 64]), .m_rresp(axm_rresp[12*2 +: 2]), .m_rlast(axm_rlast[12]), .m_rid(axm_rid[12*4 +: 4]),
        .ulpi_data(), .ulpi_dir(1'b0), .ulpi_nxt(1'b0), .ulpi_stp(), .ulpi_reset(),
        .paddr(paddr), .psel(psel_usb), .penable(penable), .pwrite(pwrite), .pwdata(pwdata), .prdata(prdata_usb), .pready(), .pslverr(), .usb_irq(plic_irq[28])
    );

    // -------------------------------------------------------
    // Security Block
    // -------------------------------------------------------
    wire trng_seed_valid;
    wire [127:0] trng_seed;

    wire [31:0] envm_addr;
    wire        envm_req;
    wire [31:0] envm_rdata;
    wire        envm_valid;

    secure_boot u_secure_boot (
        .clk(clk), .rst_n(rst_n),
        .paddr(paddr), .psel(psel_boot), .penable(penable), .pwrite(pwrite), .pwdata(pwdata), .prdata(prdata_boot), .pready(), .pslverr(),
        .envm_addr(envm_addr), .envm_req(envm_req), .envm_rdata(envm_rdata), .envm_valid(envm_valid),
        .boot_pass(boot_pass), .boot_fail(boot_fail)
    );

    envm_ctrl u_envm (
        .clk(clk), .rst_n(rst_n),
        .s_arvalid(1'b0), .s_arready(), .s_araddr(32'h0), .s_rvalid(), .s_rready(1'b0), .s_rdata(), .s_rresp(),
        .paddr(paddr), .psel(psel_envm), .penable(penable), .pwrite(pwrite), .pwdata(pwdata), .prdata(prdata_envm), .pready(), .pslverr(),
        .envm_clk(), .envm_ce_n(), .envm_we_n(), .envm_addr(), .envm_wdata(), .envm_rdata(32'h0), .envm_ready(1'b1)
    );

    drbg u_drbg (
        .clk(clk), .rst_n(rst_n),
        .paddr(paddr), .psel(psel_drbg), .penable(penable), .pwrite(pwrite), .pwdata(pwdata), .prdata(prdata_drbg), .pready(), .pslverr(),
        .trng_entropy(trng_seed), .trng_valid(trng_seed_valid), .trng_ready(),
        .drbg_irq(plic_irq[10])
    );

    aes_engine u_aes (
        .clk(clk), .rst_n(rst_n),
        .paddr(paddr), .psel(psel_aes), .penable(penable), .pwrite(pwrite), .pwdata(pwdata), .prdata(prdata_aes), .pready(), .pslverr(),
        .s_axis_tdata(32'h0), .s_axis_tvalid(1'b0), .s_axis_tready(), .s_axis_tlast(1'b0),
        .m_axis_tdata(), .m_axis_tvalid(), .m_axis_tready(1'b0), .m_axis_tlast(),
        .aes_irq(plic_irq[11])
    );

    // -------------------------------------------------------
    // Low-Speed Peripherals
    // -------------------------------------------------------
    rtc u_rtc (
        .clk(clk), .rtc_clk(rtc_clk), .rst_n(rst_n),
        .paddr(paddr), .psel(psel_rtc), .penable(penable), .pwrite(pwrite), .pwdata(pwdata),
        .prdata(prdata_rtc), .pready(), .pslverr(),
        .timer_irq(timer_irq)
    );

    uart_16550 u_uart0 (.clk(clk), .rst_n(rst_n), .paddr(paddr), .psel(psel_uart0), .penable(penable), .pwrite(pwrite), .pwdata(pwdata), .prdata(prdata_uart0), .pready(), .pslverr(), .uart_irq(plic_irq[20]), .rxd(uart_rx[0]), .txd(uart_tx[0]), .irda_tx(), .irda_rx(1'b0), .lin_tx(), .lin_rx(1'b1));
    uart_16550 u_uart1 (.clk(clk), .rst_n(rst_n), .paddr(paddr), .psel(psel_uart1), .penable(penable), .pwrite(pwrite), .pwdata(pwdata), .prdata(prdata_uart1), .pready(), .pslverr(), .uart_irq(plic_irq[21]), .rxd(uart_rx[1]), .txd(uart_tx[1]), .irda_tx(), .irda_rx(1'b0), .lin_tx(), .lin_rx(1'b1));
    uart_16550 u_uart2 (.clk(clk), .rst_n(rst_n), .paddr(paddr), .psel(psel_uart2), .penable(penable), .pwrite(pwrite), .pwdata(pwdata), .prdata(prdata_uart2), .pready(), .pslverr(), .uart_irq(plic_irq[22]), .rxd(uart_rx[2]), .txd(uart_tx[2]), .irda_tx(), .irda_rx(1'b0), .lin_tx(), .lin_rx(1'b1));
    uart_16550 u_uart3 (.clk(clk), .rst_n(rst_n), .paddr(paddr), .psel(psel_uart3), .penable(penable), .pwrite(pwrite), .pwdata(pwdata), .prdata(prdata_uart3), .pready(), .pslverr(), .uart_irq(plic_irq[23]), .rxd(uart_rx[3]), .txd(uart_tx[3]), .irda_tx(), .irda_rx(1'b0), .lin_tx(), .lin_rx(1'b1));
    uart_16550 u_uart4 (.clk(clk), .rst_n(rst_n), .paddr(paddr), .psel(psel_uart4), .penable(penable), .pwrite(pwrite), .pwdata(pwdata), .prdata(prdata_uart4), .pready(), .pslverr(), .uart_irq(plic_irq[24]), .rxd(uart_rx[4]), .txd(uart_tx[4]), .irda_tx(), .irda_rx(1'b0), .lin_tx(), .lin_rx(1'b1));

    can_controller u_can0 (.clk(clk), .rst_n(rst_n), .paddr(paddr), .psel(psel_can0), .penable(penable), .pwrite(pwrite), .pwdata(pwdata), .prdata(prdata_can0), .pready(), .pslverr(), .can_irq(plic_irq[25]), .can_tx(can_tx[0]), .can_rx(can_rx[0]));
    can_controller u_can1 (.clk(clk), .rst_n(rst_n), .paddr(paddr), .psel(psel_can1), .penable(penable), .pwrite(pwrite), .pwdata(pwdata), .prdata(prdata_can1), .pready(), .pslverr(), .can_irq(plic_irq[26]), .can_tx(can_tx[1]), .can_rx(can_rx[1]));

    // -------------------------------------------------------
    // Video Subsystem
    // -------------------------------------------------------
    wire [31:0] isp_tdata;
    wire isp_tvalid, isp_tlast, isp_tuser, isp_tready;

    mipi_csi2_rx u_mipi (
        .rst_n(rst_n), .rxbyteclkhs(mipi_rxbyteclkhs),
        .m_axis_tdata(isp_tdata), .m_axis_tvalid(isp_tvalid), .m_axis_tready(isp_tready), .m_axis_tuser(isp_tuser), .m_axis_tlast(isp_tlast),
        .pclk(clk), .prst_n(rst_n), .paddr(paddr), .psel(psel_mipi), .penable(penable), .pwrite(pwrite), .pwdata(pwdata), .prdata(prdata_mipi), .pready(), .pslverr(),
        .rxdatahs(32'h0), .rxvalidhs(4'h0), .rxactivehs(4'h0), .rxsyncbhs(4'h0), .rxdata_lp(8'h0)
    );

    isp_pipeline u_isp (
        .clk(clk), .rst_n(rst_n),
        .s_axis_tdata(isp_tdata), .s_axis_tvalid(isp_tvalid), .s_axis_tready(isp_tready), .s_axis_tuser(isp_tuser), .s_axis_tlast(isp_tlast),
        .m_axis_tdata(), .m_axis_tvalid(), .m_axis_tready(1'b1), .m_axis_tlast(), .m_axis_tuser(),
        .paddr(paddr), .psel(psel_isp), .penable(penable), .pwrite(pwrite), .pwdata(pwdata), .prdata(prdata_isp), .pready(), .pslverr()
    );

    hdmi_ctrl u_hdmi (
        .clk_pixel(hdmi_clk_pixel), .clk_tmds(hdmi_clk_tmds), .rst_n(rst_n),
        .s_axis_tdata(32'h0), .s_axis_tvalid(1'b0), .s_axis_tready(), .s_axis_tuser(1'b0), .s_axis_tlast(1'b0),
        .tmds_clk_p(hdmi_tmds_clk_p), .tmds_clk_n(hdmi_tmds_clk_n),
        .tmds_data_p(hdmi_tmds_data_p), .tmds_data_n(hdmi_tmds_data_n),
        .pclk(clk), .prst_n(rst_n), .paddr(paddr), .psel(psel_hdmi), .penable(penable), .pwrite(pwrite), .pwdata(pwdata), .prdata(prdata_hdmi), .pready(), .pslverr()
    );

endmodule
