../../video/vdma/vdma.v
../../video/hdmi_ctrl/hdmi_ctrl.v
../../video/mipi_csi2_rx/mipi_csi2_rx.v
../../video/isp_pipeline/isp_pipeline.v
../../backend/rv_ptw/rv_ptw.v
../../backend/rv_pmp/rv_pmp.v
../../backend/plic/plic.v
../../backend/rv_execute/rv_execute.v
../../backend/rv_fpu/rv_fpu.v
../../backend/rv_core_top/rv_core_top.v
../../backend/rv_tlb/rv_tlb.v
../../backend/rv_dcache/rv_dcache.v
../../backend/clint/clint.v
../../backend/rv_writeback/rv_writeback.v
../../backend/rv_monitor_core/rv_monitor_core.v
../../backend/rv_mem/rv_mem.v
../../backend/rv_mmu/rv_mmu.v
../../backend/rv_debug/rv_debug.v
../../interconnect/axi4_crossbar/axi4_crossbar.v
../../interconnect/apb_bridge/apb_bridge.v
../../interconnect/axi4_to_ahb/axi4_to_ahb.v
../../interconnect/qos_controller/qos_controller.v
../../interconnect/ahb_to_apb/ahb_to_apb.v
../../interconnect/interconnect_mpu/mpu.v
../../interconnect/mmu_arbiter/mmu_arbiter.v
../../peripherals/pcie_top/pcie_top.v
../../peripherals/gpio_ctrl/gpio_ctrl.v
../../peripherals/i2c_master/i2c_master.v
../../peripherals/can_controller/can_controller.v
../../peripherals/gem_sgmii_pcs/gem_sgmii_pcs.v
../../peripherals/pcie_pipe_if/pcie_pipe_if.v
../../peripherals/gem_ethernet/gem_ethernet.v
../../peripherals/uart_16550/uart_16550.v
../../peripherals/trng/trng.v
../../peripherals/aes_engine/aes_engine.v
../../peripherals/watchdog_timer/watchdog_timer.v
../../peripherals/spi_master/spi_master.v
../../peripherals/sha256_engine/sha256_engine.v
../../peripherals/rtc/rtc.v
../../frontend/rv_decode/rv_decode.v
../../frontend/rv_icache/rv_icache.v
../../frontend/rv_bpu/rv_bpu.v
../../frontend/rv_fetch/rv_fetch.v
../../common/cdc_sync/cdc_sync.v
../../common/fifo_sync/fifo_sync.v
../../common/fifo_async/fifo_async.v
../../common/reset_sync/reset_sync.v
../../common/BUFX4/buf_macros.v
../../memory/l2_data_array/l2_data_array.v
../../memory/ddr_scheduler/ddr_scheduler.v
../../memory/l2_snoop_filter/l2_snoop_filter.v
../../memory/l2_cache_ctrl/l2_cache_ctrl.v
../../memory/ddr_ctrl_top/ddr_ctrl_top.v
../../memory/sram_512kx8_180nm/sram_512kx8_180nm.v
../../memory/sram_32x64_180nm/sram_32x64_180nm.v
../../memory/l2_cache_top/l2_cache_top.v
../../memory/l2_tag_array/l2_tag_array.v
../../memory/ddr_phy_if/ddr_phy_if.v
../../storage/usb_otg/usb_otg.v
../../storage/mmc_controller/mmc_controller.v
../../storage/qspi_controller/qspi_controller.v
../../security/envm_ctrl/envm_ctrl.v
../../security/drbg/drbg.v
../../security/ecdsa_engine/ecdsa_engine.v
../../security/secure_boot/secure_boot.v
