set sigs [list]
lappend sigs "tb_axi4_crossbar.m_awready"
lappend sigs "tb_axi4_crossbar.m_wready"
lappend sigs "tb_axi4_crossbar.m_bvalid"
lappend sigs "tb_axi4_crossbar.m_bresp"
lappend sigs "tb_axi4_crossbar.m_bid"
lappend sigs "tb_axi4_crossbar.m_arready"
lappend sigs "tb_axi4_crossbar.m_rvalid"
lappend sigs "tb_axi4_crossbar.m_rdata"
lappend sigs "tb_axi4_crossbar.m_rresp"
lappend sigs "tb_axi4_crossbar.m_rlast"
lappend sigs "tb_axi4_crossbar.m_rid"
lappend sigs "tb_axi4_crossbar.s_awvalid"
lappend sigs "tb_axi4_crossbar.s_awaddr"
lappend sigs "tb_axi4_crossbar.s_awid"
lappend sigs "tb_axi4_crossbar.s_wvalid"
lappend sigs "tb_axi4_crossbar.s_wdata"
lappend sigs "tb_axi4_crossbar.s_wstrb"
lappend sigs "tb_axi4_crossbar.s_wlast"
lappend sigs "tb_axi4_crossbar.s_bready"
lappend sigs "tb_axi4_crossbar.s_arvalid"
lappend sigs "tb_axi4_crossbar.s_araddr"
lappend sigs "tb_axi4_crossbar.s_arid"
lappend sigs "tb_axi4_crossbar.s_rready"
gtkwave::addSignalsFromList $sigs
gtkwave::setZoomFactor -18
gtkwave::setWindowStartTime 0
