set sigs [list]
lappend sigs "tb_usb_otg.clk"
lappend sigs "tb_usb_otg.rst_n"
lappend sigs "tb_usb_otg.ulpi_clk"
lappend sigs "tb_usb_otg.ulpi_dir"
lappend sigs "tb_usb_otg.ulpi_nxt"
lappend sigs "tb_usb_otg.m_awready"
lappend sigs "tb_usb_otg.m_wready"
lappend sigs "tb_usb_otg.m_bvalid"
lappend sigs "tb_usb_otg.m_bresp"
lappend sigs "tb_usb_otg.m_bid"
lappend sigs "tb_usb_otg.m_arready"
lappend sigs "tb_usb_otg.m_rvalid"
lappend sigs "tb_usb_otg.m_rdata"
lappend sigs "tb_usb_otg.m_rresp"
lappend sigs "tb_usb_otg.m_rlast"
lappend sigs "tb_usb_otg.m_rid"
lappend sigs "tb_usb_otg.paddr"
lappend sigs "tb_usb_otg.psel"
lappend sigs "tb_usb_otg.penable"
lappend sigs "tb_usb_otg.pwrite"
lappend sigs "tb_usb_otg.pwdata"
gtkwave::addSignalsFromList $sigs
gtkwave::setZoomFactor -18
gtkwave::setWindowStartTime 0
