set sigs [list]
lappend sigs "tb_ddr_ctrl_top.s_awready"
lappend sigs "tb_ddr_ctrl_top.s_wready"
lappend sigs "tb_ddr_ctrl_top.s_bvalid"
lappend sigs "tb_ddr_ctrl_top.s_bresp"
lappend sigs "tb_ddr_ctrl_top.s_bid"
lappend sigs "tb_ddr_ctrl_top.s_arready"
lappend sigs "tb_ddr_ctrl_top.s_rvalid"
lappend sigs "tb_ddr_ctrl_top.s_rdata"
lappend sigs "tb_ddr_ctrl_top.s_rresp"
lappend sigs "tb_ddr_ctrl_top.s_rlast"
lappend sigs "tb_ddr_ctrl_top.s_rid"
lappend sigs "tb_ddr_ctrl_top.ddr_ck_p"
lappend sigs "tb_ddr_ctrl_top.ddr_ck_n"
lappend sigs "tb_ddr_ctrl_top.ddr_cke"
lappend sigs "tb_ddr_ctrl_top.ddr_cs_n"
lappend sigs "tb_ddr_ctrl_top.ddr_ras_n"
lappend sigs "tb_ddr_ctrl_top.ddr_cas_n"
lappend sigs "tb_ddr_ctrl_top.ddr_we_n"
lappend sigs "tb_ddr_ctrl_top.ddr_ba"
lappend sigs "tb_ddr_ctrl_top.ddr_bg"
lappend sigs "tb_ddr_ctrl_top.ddr_addr"
lappend sigs "tb_ddr_ctrl_top.ddr_dm"
lappend sigs "tb_ddr_ctrl_top.clk"
lappend sigs "tb_ddr_ctrl_top.rst_n"
lappend sigs "tb_ddr_ctrl_top.s_awvalid"
lappend sigs "tb_ddr_ctrl_top.s_awaddr"
lappend sigs "tb_ddr_ctrl_top.s_awid"
lappend sigs "tb_ddr_ctrl_top.s_awlen"
lappend sigs "tb_ddr_ctrl_top.s_awsize"
lappend sigs "tb_ddr_ctrl_top.s_wvalid"
lappend sigs "tb_ddr_ctrl_top.s_wdata"
lappend sigs "tb_ddr_ctrl_top.s_wstrb"
lappend sigs "tb_ddr_ctrl_top.s_wlast"
lappend sigs "tb_ddr_ctrl_top.s_bready"
lappend sigs "tb_ddr_ctrl_top.s_arvalid"
lappend sigs "tb_ddr_ctrl_top.s_araddr"
lappend sigs "tb_ddr_ctrl_top.s_arid"
lappend sigs "tb_ddr_ctrl_top.s_arlen"
lappend sigs "tb_ddr_ctrl_top.s_rready"
gtkwave::addSignalsFromList $sigs
gtkwave::/Time/Zoom/Zoom_Full
gtkwave::/Time/Zoom/Zoom_In
gtkwave::/Time/Zoom/Zoom_In
gtkwave::/Time/Zoom/Zoom_In
