set sigs [list]
lappend sigs "tb_axi4_to_ahb.s_awready"
lappend sigs "tb_axi4_to_ahb.s_wready"
lappend sigs "tb_axi4_to_ahb.s_bvalid"
lappend sigs "tb_axi4_to_ahb.s_bresp"
lappend sigs "tb_axi4_to_ahb.s_bid"
lappend sigs "tb_axi4_to_ahb.s_arready"
lappend sigs "tb_axi4_to_ahb.s_rvalid"
lappend sigs "tb_axi4_to_ahb.s_rdata"
lappend sigs "tb_axi4_to_ahb.s_rresp"
lappend sigs "tb_axi4_to_ahb.s_rlast"
lappend sigs "tb_axi4_to_ahb.haddr"
lappend sigs "tb_axi4_to_ahb.hwrite"
lappend sigs "tb_axi4_to_ahb.htrans"
lappend sigs "tb_axi4_to_ahb.hsize"
lappend sigs "tb_axi4_to_ahb.hburst"
lappend sigs "tb_axi4_to_ahb.hwdata"
lappend sigs "tb_axi4_to_ahb.clk"
lappend sigs "tb_axi4_to_ahb.rst_n"
lappend sigs "tb_axi4_to_ahb.s_awvalid"
lappend sigs "tb_axi4_to_ahb.s_awaddr"
lappend sigs "tb_axi4_to_ahb.s_awid"
lappend sigs "tb_axi4_to_ahb.s_wvalid"
lappend sigs "tb_axi4_to_ahb.s_wdata"
lappend sigs "tb_axi4_to_ahb.s_wstrb"
lappend sigs "tb_axi4_to_ahb.s_bready"
lappend sigs "tb_axi4_to_ahb.s_arvalid"
lappend sigs "tb_axi4_to_ahb.s_araddr"
lappend sigs "tb_axi4_to_ahb.s_arid"
lappend sigs "tb_axi4_to_ahb.s_rready"
lappend sigs "tb_axi4_to_ahb.hrdata"
lappend sigs "tb_axi4_to_ahb.hready"
lappend sigs "tb_axi4_to_ahb.hresp"
gtkwave::addSignalsFromList $sigs
gtkwave::/Time/Zoom/Zoom_Full
gtkwave::/Time/Zoom/Zoom_In
gtkwave::/Time/Zoom/Zoom_In
gtkwave::/Time/Zoom/Zoom_In
