set sigs [list]
lappend sigs "tb_rv_core_top.imem_arvalid"
lappend sigs "tb_rv_core_top.imem_araddr"
lappend sigs "tb_rv_core_top.imem_arlen"
lappend sigs "tb_rv_core_top.imem_arsize"
lappend sigs "tb_rv_core_top.imem_arburst"
lappend sigs "tb_rv_core_top.imem_rready"
lappend sigs "tb_rv_core_top.dmem_awvalid"
lappend sigs "tb_rv_core_top.dmem_awaddr"
lappend sigs "tb_rv_core_top.dmem_awlen"
lappend sigs "tb_rv_core_top.dmem_awsize"
lappend sigs "tb_rv_core_top.dmem_awburst"
lappend sigs "tb_rv_core_top.dmem_wvalid"
lappend sigs "tb_rv_core_top.dmem_wdata"
lappend sigs "tb_rv_core_top.dmem_wstrb"
lappend sigs "tb_rv_core_top.dmem_wlast"
lappend sigs "tb_rv_core_top.dmem_bready"
lappend sigs "tb_rv_core_top.dmem_arvalid"
lappend sigs "tb_rv_core_top.dmem_araddr"
lappend sigs "tb_rv_core_top.dmem_arlen"
lappend sigs "tb_rv_core_top.dmem_arsize"
lappend sigs "tb_rv_core_top.dmem_arburst"
lappend sigs "tb_rv_core_top.dmem_arlock"
lappend sigs "tb_rv_core_top.dmem_rready"
lappend sigs "tb_rv_core_top.snoop_ack"
lappend sigs "tb_rv_core_top.snoop_data_valid"
lappend sigs "tb_rv_core_top.snoop_data"
lappend sigs "tb_rv_core_top.hart_halted"
lappend sigs "tb_rv_core_top.hart_running"
gtkwave::addSignalsFromList $sigs
gtkwave::setZoomFactor -18
gtkwave::setWindowStartTime 0
